[build]
  command = "bash build.sh"
  publish = "HOMEPAGE/HOMEPAGE"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"

[dev]
  command = "npm run dev"
  targetPort = 8080
  publish = "HOMEPAGE/HOMEPAGE"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/AI"
  to = "/.netlify/functions/api/AI"
  status = 200

[[redirects]]
  from = "/about"
  to = "/.netlify/functions/api/about"
  status = 200

[[redirects]]
  from = "/status"
  to = "/.netlify/functions/api/status"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
